#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
grep -q 'class TecTacSchedule' "$ROOT/framwork/tec_tac/models.py"
grep -q 'register_scheduled_action' "$ROOT/framwork/tec_tac/scheduler.py"
grep -q 'tec_tac.execute_schedule_run' "$ROOT/framwork/tec_tac/tasks.py"
grep -q 'scheduler/schedules/' "$ROOT/framwork/tec_tac/urls.py"
grep -q 'tec-tac-scheduler.timer' "$ROOT/install.sh"
grep -q 'migrate tec_tac' "$ROOT/install.sh"
grep -q 'class TecTacSchedulerConfig' "$ROOT/framwork/tec_tac/models.py"
grep -q 'cleanup_once_schedules' "$ROOT/framwork/tec_tac/scheduler.py"
grep -q 'SchedulerPermanentError' "$ROOT/framwork/tec_tac/scheduler.py"
grep -q 'scheduler/config/' "$ROOT/framwork/tec_tac/urls.py"
grep -q 'scheduler/health/' "$ROOT/framwork/tec_tac/urls.py"
grep -q 'scheduler/self-test/' "$ROOT/framwork/tec_tac/urls.py"
grep -q 'INTERVAL = "interval"' "$ROOT/framwork/tec_tac/models.py"
grep -q 'interval_seconds = models.PositiveIntegerField' "$ROOT/framwork/tec_tac/models.py"
grep -q 'interval_anchor_at = models.DateTimeField' "$ROOT/framwork/tec_tac/models.py"
grep -q 'owner_key = models.CharField' "$ROOT/framwork/tec_tac/models.py"
grep -q 'tectac_sched_owner_unique' "$ROOT/framwork/tec_tac/models.py"
grep -q 'MIN_INTERVAL_SECONDS = 60' "$ROOT/framwork/tec_tac/scheduler.py"
grep -q '^def reconcile_schedule' "$ROOT/framwork/tec_tac/scheduler.py"
grep -q '^def disable_owned_schedule' "$ROOT/framwork/tec_tac/scheduler.py"
grep -q '^def remove_owned_schedule' "$ROOT/framwork/tec_tac/scheduler.py"
grep -qi 'interval policy schedules and reconciliation' "$ROOT/docs/module-scheduling.md"
echo 'scheduler foundation: PASS'
