<script setup>
import { computed, inject, onBeforeUnmount, onMounted, ref } from 'vue'
import { checkModuleRemoval, getModuleJob, inspectModulePackages, installModuleArtifact, listModules, removeModule, setModuleEnabled } from '../modules'
const state=inject('tecTacState'); const modules=ref([]); const loading=ref(true); const error=ref(''); const query=ref(''); const selectedId=ref(null); const managerAllowed=ref(false); const fileInput=ref(null); const inspecting=ref(false); const staged=ref(null); const activeJob=ref(null); const confirmTarget=ref(null); const confirmMode=ref(''); const confirmText=ref(''); const cascade=ref(false); let pollTimer=null
const canManage=computed(()=>managerAllowed.value&&state.context.capabilities?.manage_modules!==false)
const filtered=computed(()=>modules.value.filter(x=>!query.value.trim()||[x.id,x.status,x.extension_version].some(v=>String(v||'').toLowerCase().includes(query.value.toLowerCase()))))
const selected=computed(()=>modules.value.find(x=>x.id===selectedId.value)||null)
const enabledCount=computed(()=>modules.value.filter(x=>x.managed&&x.enabled).length); const disabledCount=computed(()=>modules.value.filter(x=>x.managed&&!x.enabled).length); const dependencyCount=computed(()=>modules.value.reduce((n,x)=>n+Object.keys(x.dependencies||{}).length,0)); const jobRunning=computed(()=>activeJob.value&&!['succeeded','failed','dispatch_failed'].includes(activeJob.value.status))
async function refresh(preferred=null){error.value='';try{const p=await listModules();modules.value=p.modules||[];managerAllowed.value=!!p.manage;selectedId.value=(preferred&&modules.value.some(x=>x.id===preferred))?preferred:(modules.value.some(x=>x.id===selectedId.value)?selectedId.value:modules.value[0]?.id||null)}catch(e){error.value=e.message||'Unable to load modules.'}finally{loading.value=false}}
function pick(){if(canManage.value&&!jobRunning.value)fileInput.value?.click()}
async function filesChosen(e){const files=[...(e.target.files||[])];e.target.value='';if(!files.length)return;inspecting.value=true;error.value='';try{staged.value=await inspectModulePackages(files)}catch(err){error.value=err.message||'Inspection failed.'}finally{inspecting.value=false}}
const preview=computed(()=>staged.value?.preview||staged.value); const plan=computed(()=>preview.value?.plan||staged.value?.plan||null); const artifactKind=computed(()=>staged.value?.kind||preview.value?.kind||'artifact')
async function install(){if(!staged.value?.upload_id||plan.value?.valid===false)return;try{const j=await installModuleArtifact(staged.value.upload_id,artifactKind.value==='batch'?'batch':'artifact');staged.value=null;beginPoll(j)}catch(e){error.value=e.message}}
function ask(item,mode){confirmTarget.value=item;confirmMode.value=mode;confirmText.value='';cascade.value=false}
function closeConfirm(){confirmTarget.value=null;confirmMode.value='';confirmText.value='';cascade.value=false}
async function confirmAction(){const item=confirmTarget.value;if(!item||confirmText.value!==item.id)return;try{let j;if(confirmMode.value==='enable')j=await setModuleEnabled(item.id,true);else if(confirmMode.value==='disable')j=await setModuleEnabled(item.id,false,cascade.value);else{const check=await checkModuleRemoval(item.id);if(!check.valid)throw new Error(`Cannot remove: required by ${check.dependants.map(x=>x.id).join(', ')}`);j=await removeModule(item.id)}closeConfirm();beginPoll(j)}catch(e){error.value=e.message}}
function beginPoll(job){activeJob.value=job;clearTimeout(pollTimer);pollTimer=setTimeout(poll,700)}
async function poll(){if(!activeJob.value?.id)return;try{activeJob.value=await getModuleJob(activeJob.value.id);if(['succeeded','failed','dispatch_failed'].includes(activeJob.value.status)){if(activeJob.value.status==='succeeded')await refresh(activeJob.value.plugin_id);return}}catch{}pollTimer=setTimeout(poll,1800)}
function reloadTecTac(){window.location.reload()}
onMounted(refresh);onBeforeUnmount(()=>clearTimeout(pollTimer))
</script>
<template><section>
<div class="phead"><div><span class="eyebrow">MODULE MANAGEMENT V2</span><h1>Modules</h1><p>Install packages or bundles, control runtime state, and validate dependency/version requirements before Tec-Tac changes anything.</p></div><div class="module-head-actions"><input ref="fileInput" class="sr-only" type="file" multiple accept=".zip,.tgz,.gz,application/zip,application/gzip" @change="filesChosen"><button class="btn primary" :disabled="!canManage||inspecting||jobRunning" @click="pick">{{ inspecting?'Inspecting…':'+ Install packages / bundle' }}</button></div></div>
<div v-if="error" class="auth-error">{{ error }}</div><div v-if="!canManage&&!loading" class="state-inline warning"><b>Read-only module catalog.</b> Tactical <span class="mono">can_do_server_maint</span> is required.</div>
<div class="grid g4 mb"><article class="tile"><div class="lbl">Installed</div><div class="big">{{ modules.filter(x=>x.managed).length }}</div><div class="brk">managed modules</div></article><article class="tile"><div class="lbl">Enabled</div><div class="big">{{ enabledCount }}</div><div class="brk">active at runtime</div></article><article class="tile"><div class="lbl">Disabled</div><div class="big">{{ disabledCount }}</div><div class="brk">installed, inactive</div></article><article class="tile"><div class="lbl">Dependencies</div><div class="big">{{ dependencyCount }}</div><div class="brk">hard dependency links</div></article></div>
<div v-if="loading" class="callout mono">Loading Module Management v2 catalog…</div><div v-else class="module-layout"><div><div class="toolbar"><label class="compact-input"><input v-model="query" placeholder="Search modules…"></label><span class="muted mono">{{ filtered.length }} shown</span><span class="spacer"></span><button class="btn sm" @click="refresh(selectedId)">Refresh</button></div><div class="tablewrap"><table><thead><tr><th>Module</th><th>Version</th><th>Runtime</th><th>Dependencies</th><th>Dependants</th><th>UI</th><th>Status</th></tr></thead><tbody><tr v-for="item in filtered" :key="item.id" class="clickrow" :class="{selected:selectedId===item.id}" @click="selectedId=item.id"><td><b>{{ item.id }}</b><span v-if="item.protected" class="sub">protected</span></td><td class="mono">{{ item.extension_version||'—' }}</td><td><span class="pill" :class="item.enabled?'ok':'warn'">{{ item.enabled?'enabled':'disabled' }}</span></td><td class="mono">{{ Object.keys(item.dependencies||{}).length }}</td><td class="mono">{{ item.dependants?.length||0 }}</td><td>{{ item.authenticated_ui_enabled?'admin':(item.public_ui_enabled?'public':'—') }}</td><td><span class="pill" :class="item.status==='enabled'?'ok':'warn'">{{ item.status }}</span></td></tr></tbody></table></div></div>
<aside v-if="selected" class="module-detail card"><div class="cardhead"><div><span class="eyebrow">MODULE DETAIL</span><h3>{{ selected.id }}</h3></div><span class="pill" :class="selected.enabled?'ok':'warn'">{{ selected.enabled?'ENABLED':'DISABLED' }}</span></div><dl class="kvlist module-kv"><dt>Extension</dt><dd class="mono">v{{ selected.extension_version }}</dd><dt>ReportSet</dt><dd class="mono">v{{ selected.reportset_version }}</dd><dt>Managed</dt><dd>{{ selected.managed?'yes':'no' }}</dd><dt>Permissions</dt><dd>{{ selected.permission_count||0 }}</dd></dl><div class="section-divider">Hard dependencies</div><div v-if="!Object.keys(selected.dependencies||{}).length" class="muted smalltext">None</div><div v-for="(constraint,id) in selected.dependencies" :key="id" class="module-meta"><b>{{ id }}</b><span class="mono">{{ constraint }}</span></div><div class="section-divider">Required by</div><div v-if="!selected.dependants?.length" class="muted smalltext">No installed dependants</div><div v-for="d in selected.dependants" :key="d.id" class="module-meta"><b>{{ d.id }}</b><span class="mono">{{ d.constraint }}</span></div><div v-if="selected.runtime_requirements?.length" class="section-divider">Runtime requirements</div><div v-for="r in selected.runtime_requirements" :key="r.component" class="module-meta"><b>{{ r.component }}</b><span class="mono">{{ r.current||'unknown' }} / {{ r.constraint }} {{ r.satisfied?'✓':'✕' }}</span></div><div v-if="selected.managed" class="module-actions"><button v-if="selected.enabled" class="btn warnbtn" :disabled="!canManage||jobRunning" @click="ask(selected,'disable')">Disable</button><button v-else class="btn primary" :disabled="!canManage||jobRunning" @click="ask(selected,'enable')">Enable</button><button class="btn danger" :disabled="!canManage||jobRunning" @click="ask(selected,'remove')">Remove</button></div></aside></div>
<div v-if="activeJob" class="job-panel card mt"><div class="cardhead"><div><span class="eyebrow">MODULE JOB</span><h3>{{ activeJob.action }} / {{ activeJob.plugin_id }}</h3></div><span class="pill" :class="activeJob.status==='succeeded'?'ok':'warn'">{{ activeJob.status }}</span></div><div v-if="activeJob.error" class="auth-error">{{ activeJob.error }}</div><pre v-if="activeJob.log_tail?.length" class="job-log">{{ activeJob.log_tail.join('\n') }}</pre><div v-if="activeJob.status==='succeeded'" class="row"><button class="btn primary" @click="reloadTecTac">Reload Tec-Tac</button></div></div>
<div v-if="staged" class="modal-backdrop" @click.self="staged=null"><section class="modal-panel module-package-dialog"><div class="cardhead"><div><span class="eyebrow">INSTALL PLAN</span><h3>{{ preview?.id||`${staged.packages?.length||0} packages` }}</h3></div><span class="pill" :class="plan?.valid?'ok':'warn'">{{ plan?.valid?'VALID':'BLOCKED' }}</span></div><div class="state-inline" :class="plan?.valid?'':'warning'"><b>{{ plan?.valid?'Dependency plan resolved.':'Installation blocked.' }}</b> {{ plan?.valid?'Packages will be installed in dependency order.':'Resolve the dependency/version problems below first.' }}</div><div class="section-divider">Execution order</div><div v-for="(a,i) in plan?.actions||[]" :key="a.id" class="module-meta"><span><b>{{ i+1 }}. {{ a.id }}</b> <span class="muted">{{ a.action }}</span></span><span class="mono">{{ a.current_version||'new' }} → {{ a.version }}</span></div><div v-if="plan?.problems?.length" class="section-divider">Blocking problems</div><div v-for="(p,i) in plan?.problems||[]" :key="i" class="state-inline warning mt"><span class="mono">{{ p.module||'plan' }}</span> — {{ p.type }}<span v-if="p.dependency">: {{ p.dependency }} {{ p.constraint }}</span></div><div class="modal-actions"><button class="btn primary" :disabled="!plan?.valid" @click="install">Install plan</button><button class="btn" @click="staged=null">Cancel</button></div></section></div>
<div v-if="confirmTarget" class="modal-backdrop" @click.self="closeConfirm"><section class="modal-panel"><div class="cardhead"><div><span class="eyebrow">{{ confirmMode.toUpperCase() }} MODULE</span><h3>{{ confirmTarget.id }}</h3></div><span class="pill warn">RUNTIME CHANGE</span></div><p v-if="confirmMode==='disable'&&confirmTarget.dependants?.length" class="compact-copy">Enabled dependants may block this action. Select cascade to disable dependent modules first.</p><label v-if="confirmMode==='disable'&&confirmTarget.dependants?.length" class="checkline warning-check"><input v-model="cascade" type="checkbox"> Disable enabled dependants as part of this job</label><label class="field"><span>Type {{ confirmTarget.id }} to confirm</span><input v-model="confirmText" autocomplete="off"></label><div class="modal-actions"><button class="btn" :class="confirmMode==='enable'?'primary':'danger'" :disabled="confirmText!==confirmTarget.id" @click="confirmAction">{{ confirmMode }} module</button><button class="btn" @click="closeConfirm">Cancel</button></div></section></div>
</section></template>
