<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import StructuredObjectEditor from '../components/StructuredObjectEditor.vue'
import { createSchedule, deleteSchedule, listScheduledActions, listScheduleRuns, listSchedules, runScheduleNow, updateSchedule } from '../scheduler'

const actions=ref([]), userSchedules=ref([]), moduleSchedules=ref([]), userRuns=ref([]), moduleRuns=ref([]), loading=ref(true), error=ref(''), notice=ref(''), saving=ref(false), selectedId=ref(null), editing=ref(false), tab=ref('user'), query=ref('')
const dangerousConfirm=ref(null), confirmText=ref(''), deleteConfirm=ref(null), deleteBusy=ref(false), forceDeleteRequired=ref(false), forceDeleteCount=ref(0), forceDeleteText=ref('')
const browserTz=Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'
const weekdays=[['Mon',0],['Tue',1],['Wed',2],['Thu',3],['Fri',4],['Sat',5],['Sun',6]]
const draft=ref(blank())
function blank(){return {name:'',action_id:'tec-tac.scheduler-test',target_mode:'snapshot',targets:{type:'none'},parameters:{message:'Tec-Tac scheduler test event executed.'},schedule_type:'once',timezone:browserTz,run_at:'',run_time:'09:00',weekdays:[0,1,2,3,4],day_of_month:1,enabled:true,missed_policy:'run_on_recovery',missed_grace_minutes:60,concurrency_policy:'skip',retry_count:0,retry_delay_seconds:60}}
const schedules=computed(()=>tab.value==='module'?moduleSchedules.value:userSchedules.value)
const runs=computed(()=>tab.value==='module-history'?moduleRuns.value:userRuns.value)
const selected=computed(()=>userSchedules.value.find(x=>x.id===selectedId.value)||null)
const userEnabledCount=computed(()=>userSchedules.value.filter(x=>x.enabled).length)
const moduleEnabledCount=computed(()=>moduleSchedules.value.filter(x=>x.enabled).length)
const enabledCount=computed(()=>schedules.value.filter(x=>x.enabled).length)
const currentOwnerRuns=computed(()=>tab.value.startsWith('module')?moduleRuns.value:userRuns.value)
const failingCount=computed(()=>currentOwnerRuns.value.filter(x=>x.status==='failed').length)
const actionById=computed(()=>Object.fromEntries(actions.value.map(x=>[x.id,x])))
const selectedAction=computed(()=>actionById.value[draft.value.action_id]||null)
const targetTypes=computed(()=>selectedAction.value?.target_types?.length?selectedAction.value.target_types:['none'])
const filteredSchedules=computed(()=>{const q=query.value.trim().toLowerCase();if(!q)return schedules.value;return schedules.value.filter(item=>[item.name,item.owner_module,item.owner_key,item.action_label,item.action_id,item.timezone,item.schedule_type,item.last_status,item.enabled?'enabled':'disabled'].some(v=>String(v||'').toLowerCase().includes(q)))})
const filteredRuns=computed(()=>{const q=query.value.trim().toLowerCase();const rows=runs.value.slice(0,100);if(!q)return rows;return rows.filter(item=>[item.schedule_name,item.owner_module,item.action_id,item.status,item.error_type,item.error,item.id,item.celery_task_id].some(v=>String(v||'').toLowerCase().includes(q)))})
function setTargetType(type){draft.value.targets={...(draft.value.targets||{}),type}}
watch(()=>draft.value.action_id,()=>{const allowed=targetTypes.value;const current=draft.value.targets?.type;if(!allowed.includes(current)) setTargetType(allowed[0]||'none')})
watch(tab,()=>{query.value='';editing.value=false;selectedId.value=null})
function localInput(iso){if(!iso)return '';const d=new Date(iso);const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function toIso(local){if(!local)return null;return new Date(local).toISOString()}
function nextLabel(iso){return iso?new Date(iso).toLocaleString():'—'}
function timingLabel(item){if(item.schedule_type==='once')return nextLabel(item.run_at);if(item.schedule_type==='interval')return `Every ${Math.max(1,Math.round(Number(item.interval_seconds||0)/60))} min`;if(item.schedule_type==='weekly')return `${(item.weekdays||[]).map(day=>weekdays.find(row=>row[1]===day)?.[0]).filter(Boolean).join(', ')} · ${(item.run_time||'').slice(0,5)}`;if(item.schedule_type==='monthly')return `Day ${item.day_of_month} · ${(item.run_time||'').slice(0,5)}`;return `Daily · ${(item.run_time||'').slice(0,5)}`}
async function refresh(){loading.value=true;error.value='';try{const [a,s,r]=await Promise.all([listScheduledActions(),listSchedules(),listScheduleRuns()]);actions.value=a.actions||[];const allSchedules=s.schedules||[];const allRuns=r.runs||[];userSchedules.value=allSchedules.filter(x=>x.owner_type!=='module');moduleSchedules.value=allSchedules.filter(x=>x.owner_type==='module');userRuns.value=allRuns.filter(x=>x.owner_type!=='module');moduleRuns.value=allRuns.filter(x=>x.owner_type==='module');if(selectedId.value&&!userSchedules.value.some(x=>x.id===selectedId.value))selectedId.value=null}catch(e){error.value=e.message||'Unable to load schedules.'}finally{loading.value=false}}
function createNew(){draft.value=blank();editing.value=true;selectedId.value=null;tab.value='user'}
function edit(item){if(item.owner_type==='module')return;selectedId.value=item.id;draft.value={...blank(),...item,targets:structuredClone(item.targets||{}),parameters:structuredClone(item.parameters||{}),run_at:localInput(item.run_at),run_time:(item.run_time||'09:00').slice(0,5),weekdays:[...(item.weekdays||[])]};editing.value=true}
function toggleDay(day){const set=new Set(draft.value.weekdays||[]);set.has(day)?set.delete(day):set.add(day);draft.value.weekdays=[...set].sort()}
function payload(){return {...draft.value,targets:structuredClone(draft.value.targets||{}),parameters:structuredClone(draft.value.parameters||{}),run_at:draft.value.schedule_type==='once'?toIso(draft.value.run_at):null,run_time:draft.value.schedule_type==='once'?null:draft.value.run_time,weekdays:draft.value.schedule_type==='weekly'?draft.value.weekdays:[],day_of_month:draft.value.schedule_type==='monthly'?Number(draft.value.day_of_month):null}}
async function save(){saving.value=true;error.value='';try{const data=payload();if(selectedId.value)await updateSchedule(selectedId.value,data);else await createSchedule(data);editing.value=false;await refresh()}catch(e){error.value=e.message||'Unable to save schedule.'}finally{saving.value=false}}
function requestDelete(item){deleteConfirm.value=item;forceDeleteRequired.value=false;forceDeleteCount.value=0;forceDeleteText.value=''}
async function removeConfirmed(force=false){const item=deleteConfirm.value;if(!item)return;if(force&&forceDeleteText.value!==item.name)return;deleteBusy.value=true;error.value='';try{await deleteSchedule(item.id,{force});deleteConfirm.value=null;forceDeleteRequired.value=false;forceDeleteCount.value=0;forceDeleteText.value='';selectedId.value=null;editing.value=false;notice.value=force?`Force deleted ${item.name}; active runs were failed and history retained.`:`Deleted ${item.name}. Execution history was retained.`;setTimeout(()=>{notice.value=''},3000);await refresh()}catch(e){if(e?.status===409&&e?.payload?.code==='active_runs'){forceDeleteRequired.value=true;forceDeleteCount.value=Number(e.payload.active_runs||0);error.value='';return}error.value=e.message||'Unable to delete schedule.'}finally{deleteBusy.value=false}}
async function executeRunNow(item){try{await runScheduleNow(item.id);notice.value=`Run queued for ${item.name}.`;setTimeout(()=>{notice.value=''},3000);await new Promise(r=>setTimeout(r,700));await refresh()}catch(e){error.value=e.message||'Unable to queue schedule run.'}}
function runNow(item){const action=actionById.value[item.action_id];if(action?.dangerous){dangerousConfirm.value=item;confirmText.value='';return}executeRunNow(item)}
async function confirmDangerous(){const item=dangerousConfirm.value;if(!item||confirmText.value!==item.name)return;dangerousConfirm.value=null;await executeRunNow(item)}
function statusClass(v){return v==='succeeded'||v==='healthy'?'ok':v==='failed'||v==='degraded'?'danger':v==='running'||v==='queued'||v==='unknown'?'warn':''}
onMounted(refresh)
</script>

<template>
<section>
  <div class="phead"><div><span class="eyebrow">OPERATIONS / CORE SCHEDULER</span><h1>Schedules</h1><p>One Core scheduling engine with separate operator-owned and module-managed work.</p></div><div class="row"><button class="btn" :disabled="loading" @click="refresh">Refresh</button><button v-if="tab==='user'||tab==='user-history'" class="btn primary" @click="createNew">New schedule</button></div></div>
  <div class="subtabs scheduler-tabs scheduler-owner-tabs"><button :class="{active:tab==='user'}" @click="tab='user'"><b>User schedules</b><span>{{userSchedules.length}} configured · {{userEnabledCount}} enabled</span></button><button :class="{active:tab==='module'}" @click="tab='module'"><b>Module schedules</b><span>{{moduleSchedules.length}} configured · {{moduleEnabledCount}} enabled</span></button><button :class="{active:tab==='user-history'}" @click="tab='user-history'"><b>User history</b><span>{{userRuns.length}} recent</span></button><button :class="{active:tab==='module-history'}" @click="tab='module-history'"><b>Module history</b><span>{{moduleRuns.length}} recent</span></button></div>
  <div v-if="error" class="auth-error">{{error}}</div><div v-if="notice" class="state-inline">{{notice}}</div>
  <div v-if="loading" class="callout mono">Loading Scheduler…</div>
  <template v-else>
    <div class="grid g4 mb"><article class="tile"><div class="lbl">User schedules</div><div class="big">{{userSchedules.length}}</div><div class="brk">operator-managed</div></article><article class="tile"><div class="lbl">Module schedules</div><div class="big">{{moduleSchedules.length}}</div><div class="brk">module-managed</div></article><article class="tile"><div class="lbl">Actions</div><div class="big">{{actions.length}}</div><div class="brk">registered by Core/modules</div></article><article class="tile"><div class="lbl">Failed</div><div class="big">{{failingCount}}</div><div class="brk">recent execution history</div></article></div>

    <div class="toolbar scheduler-toolbar"><label class="compact-input scheduler-filter"><span class="sr-only">Filter Scheduler {{tab.includes('history')?'history':'schedules'}}</span><input v-model="query" :placeholder="tab.includes('history')?'Filter run history…':'Filter schedules…'" @keydown.esc.stop.prevent="query=''"/><button v-if="query" class="icon-button" type="button" title="Clear filter" @click="query=''">×</button></label><span class="muted smalltext">{{tab.includes('history')?filteredRuns.length:filteredSchedules.length}} shown</span></div>

    <div v-if="tab==='user'||tab==='module'" class="schedule-layout" :class="{ 'has-editor': editing && tab==='user' }"><section>
      <div v-if="tab==='module'" class="state-inline"><b>Module-managed schedules.</b> Timing definitions are owned by the module that created them. Use the owning module to change or remove a schedule; Core still provides execution and history.</div>
      <div v-if="!schedules.length" class="state-inline"><b>No {{tab==='module'?'module':'user'}} schedules configured.</b><span v-if="tab==='user'"> Create a schedule to begin using registered Core and module actions.</span></div>
      <div v-else-if="!filteredSchedules.length" class="state-inline"><b>No schedules match this filter.</b> Clear the filter to show all schedules.</div>
      <div v-else class="tablewrap"><table><thead><tr><th>Schedule</th><th v-if="tab==='module'">Owner</th><th>Action</th><th>Timing</th><th>Next run</th><th>Last result</th><th>State</th><th>Action</th></tr></thead><tbody>
        <tr v-for="item in filteredSchedules" :key="item.id" :class="{clickrow:item.owner_type!=='module',selected:selectedId===item.id}" @click="edit(item)"><td><b>{{item.name}}</b><span class="sub mono">{{item.timezone}}</span></td><td v-if="tab==='module'"><b class="mono">{{item.owner_module}}</b><span class="sub mono">{{item.owner_key}}</span><span v-if="!item.action_available" class="sub dangertext">owner/action unavailable</span></td><td><b>{{item.action_label}}</b><span class="sub mono">{{item.action_id}}</span></td><td><span>{{timingLabel(item)}}</span><span class="sub mono">{{item.schedule_type}}</span></td><td class="mono">{{nextLabel(item.next_run_at)}}</td><td><span class="pill" :class="statusClass(item.last_status)">{{item.last_status||'never'}}</span></td><td><span class="pill" :class="item.enabled?'ok':'warn'">{{item.enabled?'enabled':'disabled'}}</span></td><td><button class="btn sm" :class="{warnbtn:actionById[item.action_id]?.dangerous}" :disabled="!item.action_available" :title="item.action_available?'Run now':'Owning action is not currently registered'" @click.stop="runNow(item)">Run now</button></td></tr>
      </tbody></table></div>
    </section>
    <aside v-if="editing && tab==='user'" class="card schedule-editor"><div class="cardhead"><div><span class="eyebrow">{{selectedId?'EDIT SCHEDULE':'NEW SCHEDULE'}}</span><h3>{{draft.name||'Untitled schedule'}}</h3></div><button class="iconbtn" type="button" title="Close editor" aria-label="Close schedule editor" @click="editing=false">×</button></div>
      <div v-if="selectedAction?.dangerous" class="state-inline warning"><b>Dangerous action.</b> Review target scope and parameters carefully. Run now requires typed confirmation.</div>
      <label class="field"><span>Name</span><input v-model="draft.name" autocomplete="off"></label><label class="field"><span>Action</span><select v-model="draft.action_id"><option v-for="a in actions" :key="a.id" :value="a.id">{{a.label}} · {{a.module_id}}</option></select></label>
      <div class="field-grid"><label class="field"><span>Schedule</span><select v-model="draft.schedule_type"><option value="once">Once</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label class="field"><span>Timezone</span><input v-model="draft.timezone" class="mono"></label></div>
      <label v-if="draft.schedule_type==='once'" class="field"><span>Run at</span><input v-model="draft.run_at" type="datetime-local"></label><label v-else class="field"><span>Run time</span><input v-model="draft.run_time" type="time"></label>
      <div v-if="draft.schedule_type==='weekly'" class="field"><span>Weekdays</span><div class="weekday-row"><button v-for="[label,day] in weekdays" :key="day" type="button" class="btn sm" :class="{primary:draft.weekdays.includes(day)}" @click="toggleDay(day)">{{label}}</button></div></div>
      <label v-if="draft.schedule_type==='monthly'" class="field"><span>Day of month</span><input v-model.number="draft.day_of_month" type="number" min="1" max="31"></label>
      <div class="field"><span>Targets</span><label v-if="targetTypes.length>1" class="field compact-field"><span>Target type</span><select :value="draft.targets?.type||targetTypes[0]" @change="setTargetType($event.target.value)"><option v-for="type in targetTypes" :key="type" :value="type">{{type}}</option></select></label><div v-else class="target-type-summary"><span class="muted smalltext">Target type</span><span class="pill mono">{{draft.targets?.type||targetTypes[0]}}</span></div><StructuredObjectEditor v-model="draft.targets" :exclude-keys="['type']" /></div><div class="field"><span>Parameters</span><StructuredObjectEditor v-model="draft.parameters" /></div>
      <div class="field-grid"><label class="field"><span>Missed run</span><select v-model="draft.missed_policy"><option value="skip">Skip</option><option value="run_on_recovery">Run on recovery</option><option value="expire">Expire</option></select></label><label class="field"><span>Concurrency</span><select v-model="draft.concurrency_policy"><option value="skip">Skip while running</option><option value="queue">Queue</option><option value="allow">Allow overlap</option></select></label></div>
      <div class="field-grid"><label class="field"><span>Retries</span><input v-model.number="draft.retry_count" type="number" min="0" max="10"></label><label class="field"><span>Retry delay (sec)</span><input v-model.number="draft.retry_delay_seconds" type="number" min="1"></label></div><label class="checkline"><input v-model="draft.enabled" type="checkbox"> Enabled</label>
      <div class="editor-actions"><button class="btn primary" :disabled="saving||!draft.name||!draft.action_id" @click="save">{{saving?'Saving…':'Save schedule'}}</button><button class="btn" @click="editing=false">Cancel</button><button v-if="selected" class="btn danger" @click="requestDelete(selected)">Delete</button></div>
    </aside></div>

    <section v-else-if="tab==='user-history'||tab==='module-history'">
      <div v-if="!runs.length" class="state-inline"><b>No Scheduler runs yet.</b> Execution history appears here after a schedule or Run now action executes.</div>
      <div v-else-if="!filteredRuns.length" class="state-inline"><b>No run history matches this filter.</b> Clear the filter to show recent runs.</div>
      <div v-else class="tablewrap"><table><thead><tr><th>Time</th><th>Schedule / action</th><th>Status</th><th>Attempt</th><th>Run / Celery ID</th><th>Result / Error</th></tr></thead><tbody><tr v-for="run in filteredRuns" :key="run.id"><td class="mono">{{nextLabel(run.created_at)}}</td><td><b>{{run.schedule_name}}</b><span class="sub mono">{{run.action_id}}</span></td><td><span class="pill" :class="statusClass(run.status)">{{run.status}}</span><span v-if="run.error_type" class="sub dangertext">{{run.error_type}}</span></td><td class="mono">{{run.attempt}}</td><td class="mono"><span>{{run.id}}</span><span class="sub">{{run.celery_task_id||'no celery id'}}</span></td><td class="mono schedule-result" :title="run.error || JSON.stringify(run.result||{})">{{run.error || (run.result?.message || JSON.stringify(run.result||{}))}}</td></tr></tbody></table></div>
    </section>
  </template>

  <div v-if="deleteConfirm" class="modal-backdrop" @click.self="deleteConfirm=null"><div class="modal-panel"><div class="cardhead"><div><span class="eyebrow">{{forceDeleteRequired?'ACTIVE RUNS':'CONFIRM DELETE'}}</span><h3>{{forceDeleteRequired?'Force delete':'Delete'}} {{deleteConfirm.name}}?</h3></div></div><p v-if="!forceDeleteRequired">This removes the schedule definition. Existing execution history is retained for audit and troubleshooting.</p><template v-else><div class="state-inline denied"><b>{{forceDeleteCount}} active run{{forceDeleteCount===1?'':'s'}} will be failed.</b> The schedule definition will be removed, but the failed run records and their execution snapshots remain in history.</div><label class="field"><span>Type the schedule name to confirm force delete</span><input v-model="forceDeleteText" class="mono" autocomplete="off"></label></template><div class="modal-actions"><button class="btn" :disabled="deleteBusy" @click="deleteConfirm=null">Cancel</button><button v-if="!forceDeleteRequired" class="btn danger" :disabled="deleteBusy" @click="removeConfirmed(false)">{{deleteBusy?'Deleting…':'Delete schedule'}}</button><button v-else class="btn danger" :disabled="deleteBusy||forceDeleteText!==deleteConfirm.name" @click="removeConfirmed(true)">{{deleteBusy?'Force deleting…':'Fail active runs & delete'}}</button></div></div></div>
  <div v-if="dangerousConfirm" class="modal-backdrop" @click.self="dangerousConfirm=null"><div class="modal-panel"><div class="cardhead"><div><span class="eyebrow">DANGEROUS ACTION</span><h3>Run {{dangerousConfirm.name}} now?</h3></div></div><p>This bypasses the schedule time and immediately dispatches <span class="mono">{{dangerousConfirm.action_id}}</span> against the stored target scope.</p><label class="field"><span>Type the schedule name to confirm</span><input v-model="confirmText" class="mono" autocomplete="off"></label><div class="modal-actions"><button class="btn" @click="dangerousConfirm=null">Cancel</button><button class="btn danger" :disabled="confirmText!==dangerousConfirm.name" @click="confirmDangerous">Run now</button></div></div></div>
</section>
</template>
