#!/usr/bin/env bash
# Shared Tec-Tac installation-layout loader.
TEC_TAC_CONFIG_FILE="${TEC_TAC_CONFIG_FILE:-/opt/tec-tac/etc/tec-tac.conf}"
if [[ -f "${TEC_TAC_CONFIG_FILE}" ]]; then
  # shellcheck disable=SC1090
  source "${TEC_TAC_CONFIG_FILE}"
fi
TEC_TAC_ROOT="${TEC_TAC_ROOT:-/opt/tec-tac}"
TEC_TAC_SOURCE_ROOT="${TEC_TAC_SOURCE_ROOT:-/opt/tec-tac-src}"
TEC_TAC_FRAMEWORK_SOURCE="${TEC_TAC_FRAMEWORK_SOURCE:-${TEC_TAC_SOURCE_ROOT}/framework}"
TEC_TAC_UI_SOURCE="${TEC_TAC_UI_SOURCE:-${TEC_TAC_SOURCE_ROOT}/ui}"
TEC_TAC_FRAMEWORK_ROOT="${TEC_TAC_FRAMEWORK_ROOT:-${TEC_TAC_ROOT}/framework}"
TEC_TAC_EXTENSIONS_ROOT="${TEC_TAC_EXTENSIONS_ROOT:-${TEC_TAC_ROOT}/extensions}"
TEC_TAC_REPORTSETS_ROOT="${TEC_TAC_REPORTSETS_ROOT:-${TEC_TAC_ROOT}/reportsets}"
TEC_TAC_SCRIPTS_ROOT="${TEC_TAC_SCRIPTS_ROOT:-${TEC_TAC_ROOT}/scripts}"
TEC_TAC_STATE_ROOT="${TEC_TAC_STATE_ROOT:-/var/lib/tec-tac}"
TEC_TAC_MODULE_STATE_ROOT="${TEC_TAC_MODULE_STATE_ROOT:-${TEC_TAC_STATE_ROOT}/module-manager}"
TEC_TAC_SYSTEM_UPDATE_ROOT="${TEC_TAC_SYSTEM_UPDATE_ROOT:-${TEC_TAC_STATE_ROOT}/system-updates}"
TEC_TAC_UI_DEPLOY_ROOT="${TEC_TAC_UI_DEPLOY_ROOT:-${TEC_TAC_STATE_ROOT}/ui/tec-tac}"
TACTICAL_ROOT="${TACTICAL_ROOT:-/rmm}"
TACTICAL_BACKEND_ROOT="${TACTICAL_BACKEND_ROOT:-${TACTICAL_ROOT}/api/tacticalrmm}"
TACTICAL_PYTHON="${TACTICAL_PYTHON:-${TACTICAL_ROOT}/api/env/bin/python}"
